-- MySQL Script generated by MySQL Workbench
-- Tue Nov  2 15:21:33 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Online_Retail_Database
-- -----------------------------------------------------
DROP DATABASE IF EXISTS OnlineRetailDB;
CREATE DATABASE IF NOT EXISTS OnlineRetailDB;
USE OnlineRetailDB;
-- -----------------------------------------------------
-- Table `Store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Store` ;

CREATE TABLE IF NOT EXISTS `Store` (
  `store_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`store_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Order Detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Order Detail` ;

CREATE TABLE IF NOT EXISTS `Order Detail` (
  `order_detail_id` INT NOT NULL,
  `checkout_id` VARCHAR(45) NULL,
  PRIMARY KEY (`order_detail_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Credit Card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Credit Card` ;

CREATE TABLE IF NOT EXISTS `Credit Card` (
  `credit_card_id` INT NOT NULL,
  `number` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`credit_card_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Debit Card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Debit Card` ;

CREATE TABLE IF NOT EXISTS `Debit Card` (
  `debit_card_id` INT NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`debit_card_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Payment Method`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Payment Method` ;

CREATE TABLE IF NOT EXISTS `Payment Method` (
  `payment_method_id` INT NOT NULL,
  `credit_card_id` INT NOT NULL,
  `debit_card_id` INT NOT NULL,
  PRIMARY KEY (`payment_method_id`, `credit_card_id`, `debit_card_id`),
  INDEX `credit_card_FK_idx_idx` (`credit_card_id` ASC) VISIBLE,
  INDEX `debit_card_FK_idx_idx` (`debit_card_id` ASC) VISIBLE,
  CONSTRAINT `credit_card_FK_idx`
    FOREIGN KEY (`credit_card_id`)
    REFERENCES `Credit Card` (`credit_card_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `debit_card_FK_idx`
    FOREIGN KEY (`debit_card_id`)
    REFERENCES `Debit Card` (`debit_card_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CheckOut`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CheckOut` ;

CREATE TABLE IF NOT EXISTS `CheckOut` (
  `checkout_id` INT NOT NULL,
  `order_detail_id` INT NOT NULL,
  `payment_method_id` INT NOT NULL,
  PRIMARY KEY (`checkout_id`, `order_detail_id`, `payment_method_id`),
  INDEX `order_detail_FK_idx_idx` (`order_detail_id` ASC) VISIBLE,
  INDEX `payment_method_FK_idx_idx` (`payment_method_id` ASC) VISIBLE,
  CONSTRAINT `order_detail_FK_idx`
    FOREIGN KEY (`order_detail_id`)
    REFERENCES `Order Detail` (`order_detail_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `payment_method_FK_idx`
    FOREIGN KEY (`payment_method_id`)
    REFERENCES `Payment Method` (`payment_method_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Shopping Cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Shopping Cart` ;

CREATE TABLE IF NOT EXISTS `Shopping Cart` (
  `shopping_cart_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `checkout_id` INT NOT NULL,
  PRIMARY KEY (`shopping_cart_id`, `checkout_id`),
  INDEX `checkout_FK_idx_idx` (`checkout_id` ASC) VISIBLE,
  CONSTRAINT `checkout_FK_idx`
    FOREIGN KEY (`checkout_id`)
    REFERENCES `CheckOut` (`checkout_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Email Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Email Address` ;

CREATE TABLE IF NOT EXISTS `Email Address` (
  `email_address_id` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`email_address_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Contact Number`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Contact Number` ;

CREATE TABLE IF NOT EXISTS `Contact Number` (
  `contact_number_id` INT NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`contact_number_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CustomerServices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CustomerServices` ;

CREATE TABLE IF NOT EXISTS `CustomerServices` (
  `customer_service_id` INT NOT NULL,
  `email_address_id` INT NOT NULL,
  `contact_number_id` INT NOT NULL,
  PRIMARY KEY (`customer_service_id`, `email_address_id`, `contact_number_id`),
  INDEX `email_address_FK_idx_idx` (`email_address_id` ASC) VISIBLE,
  INDEX `contact_number_FK_idx_idx` (`contact_number_id` ASC) VISIBLE,
  CONSTRAINT `email_address_FK_idx`
    FOREIGN KEY (`email_address_id`)
    REFERENCES `Email Address` (`email_address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `contact_number_FK_idx`
    FOREIGN KEY (`contact_number_id`)
    REFERENCES `Contact Number` (`contact_number_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Rating`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Rating` ;

CREATE TABLE IF NOT EXISTS `Rating` (
  `rating_id` INT NOT NULL,
  PRIMARY KEY (`rating_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Review Section`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Review Section` ;

CREATE TABLE IF NOT EXISTS `Review Section` (
  `review_section_id` INT NOT NULL,
  `rating_id` INT NOT NULL,
  PRIMARY KEY (`review_section_id`, `rating_id`),
  INDEX `rating_FK_idx_idx` (`rating_id` ASC) VISIBLE,
  CONSTRAINT `rating_FK_idx`
    FOREIGN KEY (`rating_id`)
    REFERENCES `Rating` (`rating_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Store Website`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Store Website` ;

CREATE TABLE IF NOT EXISTS `Store Website` (
  `store_website_id` INT NOT NULL,
  `shopping_cart_id` INT NOT NULL,
  `customer_service_id` INT NOT NULL,
  `review_section_id` INT NOT NULL,
  PRIMARY KEY (`store_website_id`, `shopping_cart_id`, `customer_service_id`, `review_section_id`),
  INDEX `shopping_cart_FK_idx_idx` (`shopping_cart_id` ASC) VISIBLE,
  INDEX `customer_service_FK_idx_idx` (`customer_service_id` ASC) VISIBLE,
  INDEX `reivew_section_FK_idx_idx` (`review_section_id` ASC) VISIBLE,
  CONSTRAINT `store_PK`
    FOREIGN KEY (`store_website_id`)
    REFERENCES `Store` (`store_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `shopping_cart_FK_idx`
    FOREIGN KEY (`shopping_cart_id`)
    REFERENCES `Shopping Cart` (`shopping_cart_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `customer_service_FK_idx`
    FOREIGN KEY (`customer_service_id`)
    REFERENCES `CustomerServices` (`customer_service_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `reivew_section_FK_idx`
    FOREIGN KEY (`review_section_id`)
    REFERENCES `Review Section` (`review_section_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employee` ;

CREATE TABLE IF NOT EXISTS `Employee` (
  `employee_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `employee_dob` INT NOT NULL,
  PRIMARY KEY (`employee_id`),
  CONSTRAINT `store_FK`
    FOREIGN KEY (`employee_id`)
    REFERENCES `Store` (`store_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Department` ;

CREATE TABLE IF NOT EXISTS `Department` (
  `department_id` INT NOT NULL,
  `department_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`department_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EmployeeBelongTo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EmployeeBelongTo` ;

CREATE TABLE IF NOT EXISTS `EmployeeBelongTo` (
  `employeeBelongTo_id` INT NOT NULL,
  `employee_id` INT NULL,
  `department_id` INT NULL,
  PRIMARY KEY (`employeeBelongTo_id`),
  INDEX `employee_FK_idx_idx` (`employee_id` ASC) VISIBLE,
  INDEX `department_FK_idx_idx` (`department_id` ASC) VISIBLE,
  CONSTRAINT `employee_FK_idx`
    FOREIGN KEY (`employee_id`)
    REFERENCES `Employee` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `department_FK_idx`
    FOREIGN KEY (`department_id`)
    REFERENCES `Department` (`department_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Categories` ;

CREATE TABLE IF NOT EXISTS `Categories` (
  `categories_id` INT NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`categories_id`),
  CONSTRAINT `store_website_FK_idx`
    FOREIGN KEY (`categories_id`)
    REFERENCES `Store Website` (`store_website_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Products` ;

CREATE TABLE IF NOT EXISTS `Products` (
  `products_id` INT NOT NULL,
  `descriptions` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`products_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CategoriesHasProducts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CategoriesHasProducts` ;

CREATE TABLE IF NOT EXISTS `CategoriesHasProducts` (
  `categoriesHasProducts_id` INT NOT NULL,
  `categories_id` INT NOT NULL,
  `products_id` INT NOT NULL,
  PRIMARY KEY (`categoriesHasProducts_id`, `categories_id`, `products_id`),
  INDEX `categories_FK_idx_idx` (`categories_id` ASC) VISIBLE,
  INDEX `products_FK_idx_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `categories_FK_idx`
    FOREIGN KEY (`categories_id`)
    REFERENCES `Categories` (`categories_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `products_FK_idx`
    FOREIGN KEY (`products_id`)
    REFERENCES `Products` (`products_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CustomerAccessWebsite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CustomerAccessWebsite` ;

CREATE TABLE IF NOT EXISTS `CustomerAccessWebsite` (
  `customer_access_website_id` INT NOT NULL,
  PRIMARY KEY (`customer_access_website_id`),
  CONSTRAINT `store_website_PK_idx`
    FOREIGN KEY (`customer_access_website_id`)
    REFERENCES `Store Website` (`store_website_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `User Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User Account` ;

CREATE TABLE IF NOT EXISTS `User Account` (
  `user_account_id` INT NOT NULL,
  `gmail` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_account_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Customer` ;

CREATE TABLE IF NOT EXISTS `Customer` (
  `customer_id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `useraccount_id` INT NOT NULL,
  PRIMARY KEY (`customer_id`, `useraccount_id`),
  INDEX `useraccount_FK_idx_idx` (`useraccount_id` ASC) VISIBLE,
  CONSTRAINT `customer_access_website_FK_idx`
    FOREIGN KEY (`customer_id`)
    REFERENCES `CustomerAccessWebsite` (`customer_access_website_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `useraccount_FK_idx`
    FOREIGN KEY (`useraccount_id`)
    REFERENCES `User Account` (`user_account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CustomerReviewProductDetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CustomerReviewProductDetail` ;

CREATE TABLE IF NOT EXISTS `CustomerReviewProductDetail` (
  `customer_review_productDetail_id` INT NOT NULL,
  `product_detail_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  PRIMARY KEY (`customer_review_productDetail_id`, `product_detail_id`, `customer_id`),
  INDEX `customer_PK_idx_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `customer_FK_idx`
    FOREIGN KEY (`customer_id`)
    REFERENCES `Customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProductDetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProductDetail` ;

CREATE TABLE IF NOT EXISTS `ProductDetail` (
  `product_detail_id` INT NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`product_detail_id`),
  CONSTRAINT `customer_review_priduct_detail_FK_idx`
    FOREIGN KEY (`product_detail_id`)
    REFERENCES `CustomerReviewProductDetail` (`customer_review_productDetail_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProductHasProductDetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProductHasProductDetail` ;

CREATE TABLE IF NOT EXISTS `ProductHasProductDetail` (
  `productHasProductDetail_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `product_detail_id` INT NOT NULL,
  PRIMARY KEY (`productHasProductDetail_id`, `product_id`, `product_detail_id`),
  INDEX `product_FK_idx_idx` (`product_id` ASC) VISIBLE,
  INDEX `product_detail_FK_idx_idx` (`product_detail_id` ASC) VISIBLE,
  CONSTRAINT `product_FK_idx`
    FOREIGN KEY (`product_id`)
    REFERENCES `Products` (`products_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `product_detail_FK_idx`
    FOREIGN KEY (`product_detail_id`)
    REFERENCES `ProductDetail` (`product_detail_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Comment` ;

CREATE TABLE IF NOT EXISTS `Comment` (
  `comment_id` INT NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`comment_id`),
  CONSTRAINT `review_section_FK_idx`
    FOREIGN KEY (`comment_id`)
    REFERENCES `Review Section` (`review_section_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
